#!/usr/bin/env python3
"""Generate src/huff_trie.h : HPACK Huffman decode trie from `hpack` lib tables.
Trie node: {int16_t child0, int16_t child1, int16_t sym} ; sym=-1 inner, 0..255 leaf, 256=EOS.
Run: python3 scripts/gen_huff.py  (needs: pip install hpack)
"""
import sys
sys.path.insert(0, '/data/data/com.termux/files/usr/lib/python3.14/site-packages')
from hpack.huffman_constants import REQUEST_CODES, REQUEST_CODES_LENGTH as REQUEST_CODE_LENGTHS

nodes_child = [[-1, -1]]
nodes_sym = [-1]

def insert(sym, code, nbits):
    node = 0
    for i in range(nbits - 1, -1, -1):
        bit = (code >> i) & 1
        nxt = nodes_child[node][bit]
        if nxt == -1:
            nxt = len(nodes_child)
            nodes_child[node][bit] = nxt
            nodes_child.append([-1, -1])
            nodes_sym.append(-1)
        node = nxt
    nodes_sym[node] = sym

for sym in range(257):
    insert(sym, REQUEST_CODES[sym], REQUEST_CODE_LENGTHS[sym])

n = len(nodes_child)
print(f"nodes={n}", file=sys.stderr)
L = []
L.append("// Auto-generated by scripts/gen_huff.py from python `hpack` Huffman tables")
L.append("// (RFC 7541 Appendix B). Derivative of nghttp2 tables (MIT/Apache-2.0, (c) Tatsuhiro Tsujikawa).")
L.append("#pragma once")
L.append("#include <cstdint>")
L.append("namespace asv2 { namespace huff {")
L.append(f"static const int NODES={n};")
L.append(f"static const int16_t CHILD[{n}][2]={{")
for i, (a, b) in enumerate(nodes_child):
    L.append(f"{{{a},{b}}},")
L.append("};")
L.append(f"static const int16_t SYM[{n}]={{")
for i in range(0, n, 16):
    L.append(",".join(str(nodes_sym[j]) for j in range(i, min(i + 16, n))) + ",")
L.append("};")
L.append("} } // namespace")
open('/data/data/com.termux/files/home/release/autoscript_v2/src/huff_trie.h', 'w').write("\n".join(L) + "\n")
print("wrote src/huff_trie.h")
